In [1]:
arr2D= np.array([1,2,3],
                [1,2,3])
print(arr2D)

NameError: name 'np' is not defined

In [4]:
import numpy as np
arr2D= np.array([[1,2,3],
                [1,2,3]])
print(arr2D)

[[1 2 3]
 [1 2 3]]


In [3]:
import numpy as np

# 1. CREATE ARRAYS
arr1D = np.array([10, 20, 30, 40, 50])
arr2D = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("1D Array:")
print(arr1D)
print("\n2D Array:")
print(arr2D)

# 2. OPERASI MATEMATIK
print("\nTambah 5 pada setiap elemen 1D array:")
print(arr1D + 5)

print("\nDarab setiap elemen dalam 2D array dengan 2:")
print(arr2D * 2)

# 3. SHAPE & SIZE
print("\nShape arr2D:", arr2D.shape)
print("Total elements arr2D:", arr2D.size)

# 4. INDEXING
print("\nElemen kedua dalam 1D array:", arr1D[1])
print("Elemen baris 1, kolum 2 dalam 2D array:", arr2D[0, 1])

# 5. SLICE
print("\nSlice arr1D [1:4]:", arr1D[1:4])

# 6. RANDOM ARRAY
rand_arr = np.random.randint(1, 10, (3, 3))
print("\nRandom 3x3 array:")
print(rand_arr)

# 7. SUM, MAX, MIN
print("\nJumlah keseluruhan rand_arr:", rand_arr.sum())
print("Nilai maksimum:", rand_arr.max())
print("Nilai minimum:", rand_arr.min())

1D Array:
[10 20 30 40 50]

2D Array:
[[1 2 3]
 [4 5 6]]

Tambah 5 pada setiap elemen 1D array:
[15 25 35 45 55]

Darab setiap elemen dalam 2D array dengan 2:
[[ 2  4  6]
 [ 8 10 12]]

Shape arr2D: (2, 3)
Total elements arr2D: 6

Elemen kedua dalam 1D array: 20
Elemen baris 1, kolum 2 dalam 2D array: 2

Slice arr1D [1:4]: [20 30 40]

Random 3x3 array:
[[6 1 1]
 [4 6 3]
 [8 6 7]]

Jumlah keseluruhan rand_arr: 42
Nilai maksimum: 8
Nilai minimum: 1


In [4]:
type(arr1D)

numpy.ndarray

In [5]:
print(arr1D)

[10 20 30 40 50]


In [6]:
arr1D*30

array([ 300,  600,  900, 1200, 1500])

In [12]:
arr1=np.array([1,2,3,4,5])
print(arr1)

arr2=np.array([10,20,30,40,50])
print(arr2)

print("result:",arr1+arr2)

[1 2 3 4 5]
[10 20 30 40 50]
result: [11 22 33 44 55]


In [ ]:
prices=np.array([4000000,3500000,2500000])
print(f'Tghe prices are:{prices/1000000} million')#scale data

Tghe prices are:[4.  3.5 2.5] million


slicing
reshaping

In [20]:
#only list comprehension we have
nums=[x for x in range(0,101,2)]
print(nums)
nums.size

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


AttributeError: 'list' object has no attribute 'size'

In [15]:
nums1=nums[3]
nums1

6

In [16]:
nums1=nums[0:50]
nums1

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98]

In [17]:
nums1=nums[0:100:-1]
nums1

[]

In [26]:
import numpy as np
nums=np.array([x for x in range(0,101,2)])
print(nums)

nums.size

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


51

In [28]:
import numpy as np

line = np.linspace(0, 1, 10)   # values are evenly spaced and stored in array
line


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [29]:
import numpy as np

line = np.linspace(0, 1, 10)
print(line)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [30]:
line = np.linspace(0,1,10)

line
# [
# ]


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [31]:
import numpy as np

line = np.arange(0, 1.1, 0.1)
print(line)


[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [32]:
import numpy as np

line = np.linspace(0, 1, 10)
line


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [33]:
import numpy as np
line=np.linspace(0,1,11)
print(line)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [36]:
np.random.seed(40)

randomArray=np.random.randint(0,100,(3,4))

In [37]:

# 2. Flatten array
flatarray = randomArray.flatten()
print(flatarray)

# 3. Reshape semula
reshapearray = flatarray.reshape(6, 2)
print(reshapearray)



[70 91  7 37 56 50 65 12 71 19 31 74]
[[70 91]
 [ 7 37]
 [56 50]
 [65 12]
 [71 19]
 [31 74]]


In [38]:
reshapearray.T

array([[70,  7, 56, 65, 71, 31],
       [91, 37, 50, 12, 19, 74]], dtype=int32)

In [39]:

numbers = [i for i in range(1, 11)]

total = sum(numbers)

print("List:", numbers)
print("Total:", total)


List: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Total: 55


In [46]:
array_idrees=np.array([num for num in range(1,11)])
sum_of_array_idrees=array_idrees.sum()
print(sum_of_array_idrees)
print(array_idrees.mean())

55
5.5
